ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'ro';
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "authorName" TEXT NOT NULL DEFAULT 'Editor';
ALTER TABLE "BlogArticle" ADD COLUMN IF NOT EXISTS "featuredImageUrl" TEXT;
