// app/lib/seo/decision-log.server.js
//
// Audit trail for SEO Brain decisions. Every Taxonomy + Keyword Selection
// decision logs its inputs + output + rationale so we can:
//  1. Debug "why was this keyword chosen?" 6 months later
//  2. Replay decisions when algorithm version changes
//  3. Show transparent breakdown to merchant in UI
//  4. Generate periodic reports (which algorithm version performs best)
//
// Inputs/output are JSON for flexibility (different decision types carry
// different payloads). Rationale is plain text — generated by the algorithm,
// not the user.

import prisma from "../../db.server.js";

export const DECISION_KINDS = {
  TAXONOMY_L0:           "taxonomy_l0",
  TAXONOMY_L1:           "taxonomy_l1",
  TAXONOMY_L2:           "taxonomy_l2",
  TAXONOMY_L3:           "taxonomy_l3",
  PRODUCT_KEYWORD:       "product_keyword",
  CLUSTER_SPLIT:         "cluster_split",
  MERGE_RECOMMENDATION:  "merge_recommendation",
};

const CURRENT_ALGO_VERSION = "v1_2026_05_18";

export async function logDecision({
  storeId, decisionKind, subjectKind, subjectId,
  inputs, output, rationale,
  decidedBy = CURRENT_ALGO_VERSION,
}) {
  return prisma.seoDecisionLog.create({
    data: {
      storeId, decisionKind, subjectKind, subjectId,
      inputs: inputs || {},
      output: output || {},
      rationale: rationale || null,
      decidedBy,
    },
  });
}

// Get the latest decision of a specific kind for a subject.
// Used by UI to show "Current decision + alternatives" panel.
export async function getLatestDecision({ storeId, decisionKind, subjectKind, subjectId }) {
  return prisma.seoDecisionLog.findFirst({
    where: { storeId, decisionKind, subjectKind, subjectId },
    orderBy: { createdAt: "desc" },
  });
}

// When a new decision supersedes a previous one (e.g. weekly re-eval changes
// keyword), link them. Lets us trace evolution of decisions over time.
export async function supersedeDecision(oldDecisionId, newDecisionId) {
  await prisma.seoDecisionLog.update({
    where: { id: oldDecisionId },
    data:  { supersededBy: newDecisionId },
  });
}

export async function getDecisionHistory({ storeId, subjectKind, subjectId, limit = 20 }) {
  return prisma.seoDecisionLog.findMany({
    where: { storeId, subjectKind, subjectId },
    orderBy: { createdAt: "desc" },
    take: limit,
  });
}
